name: Go CLI Application CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Specify the Go version you want to use

      # Step 3: Cache dependencies
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: go mod download

      # Step 5: Build the application
      - name: Build
        run: go build -v ./...

      # Step 6: Run tests
      - name: Test
        run: go test -v ./...
        
      # Step 7: Run the CLI application (optional)
      # This step demonstrates how to run the CLI with a sample input.
      - name: Run CLI with Sample Input
        run: go run main.go TestInput
